Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: False

Style/GuardClause:
 Enabled: False

Metrics/LineLength:
   Max: 130

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:

Layout/LineLength:
  Enabled: false

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - coverage/**/*
    - db/**/*
    - lib/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - spec/**/*
    - tmp/**/*
    - vendor/**/*
